### ISSUE TITLE
Where is some info?

### ISSUE THREAD

**Issue by Teressss** [OhGodACompany/OhGodAnETHlargementPill#1]
-

**Comment by jimmykl** [comment]
••

**Comment by Teressss** [comment]
ok, no info, well....

**Comment by OhGodAGirl** [comment]
Please kindly redirect your eyeballs to prescription.txt - that will provide you all the information you need to get started.

**Comment by Teressss** [comment]
I don't need info how to get started. I am seeking info about where and how to buy commercial version for 1060,70..
