### ISSUE TITLE
Nothing pool side

### ISSUE THREAD

**Issue by pera12345** [OhGodACompany/OhGodAnETHlargementPill#13]
I get increased hashrate but pool doesnt report that anything is mining?

**Comment by OhGodAGirl** [comment]
The pool does, and has. For _all_ users. The ones who claim otherwise usually ran it for 10 minutes and called it a day. Please, run the tool for at least 24 hours.

This isn't 'fake share' injection. If you want that, go download a ePeen miner. ;)
