### ISSUE TITLE
Not Working for 1050ti

### ISSUE THREAD

**Issue by ahmed-abdelazim** [OhGodACompany/OhGodAnETHlargementPill#15]
Please add support for 1050ti

**Comment by jimmykl** [comment]
You would have to find a 1050ti which uses GDDR5X memory ;-)

**Comment by OhGodABird** [comment]
The public edition of the pill is currently limited to work on 1080, 1080 Ti and Titan Xp, and there are no short-term plans to prescribe treatment for other models.
