### ISSUE TITLE
Why 1080s and 1080Tis?

### ISSUE THREAD

**Issue by digdug82** [OhGodACompany/OhGodAnETHlargementPill#17]
Are you planning to boost other GPUs like the 1070, 1070TI?
Also, I made a test using MSI GTX 1080TI using UBUNTU and it's showing an increase from 32-45 while windows users reporting 55.

**Comment by nemosminer** [comment]
gddr5x .........

**Comment by OhGodAGirl** [comment]
Our alternative treaments will not be public or free, since the general community likes to shit all over us for making something free, re: YouTube, GitHub, etc.

**Comment by digdug82** [comment]
Punishing 99% of users because of couple of reviewers isn't wise, I watched your interview with James from JMS vlogs and you sounded like a nice person knew what you are doing, We need people like you in the community.. and every product get critics even if the product is free, that's the human nature so don't get upset and keep up the good work.
Even If the product wasn't a good fit to me because of most of my gpus are 1070ti but I really appreciate the idea and the amount of time you spent working on the project.
I hope that you change your mind and reconsider your decision.
Thank you

**Comment by CaptainJoe66** [comment]
I could not agree with digdug more... We need more ppl like you who contributes freely to the community. Agreeing to the interview was wise. Putting a face behind the project makes it more credible.  Understandably there is always a lot of skepticism when it comes to free closed source .

Can't wait until May 25 to see your miner and other enhencments you have for us.  Please keep it up.
