### ISSUE TITLE
GTX 1080 rig crashed

### ISSUE THREAD

**Issue by GrasyPommel** [OhGodACompany/OhGodAnETHlargementPill#18]
If you keep closing my unresolved threads, I'll just keep making new ones until my issue is resolved. Some background:
I have a mining rig with GTX 1080's that I installed this tool onto. After running ETHlargement.exe as administrator, the computer crashed and has not been able to run any miners without abruptly shutting down. It has been stable for months prior to this so running ETHlargement.exe has been the only thing I've done on this rig in a long time.

What information should I provide to assist any kind souls out there who would be willing to help me resolve this? Thanks.

**Comment by OhGodABird** [comment]
As you are still not providing the information requested in the previous thread, I can only suggest restoring your system to a known working state. Please refrain from opening new threads without information that could be actually used to solve the issue.
