### ISSUE TITLE
Gtx1060 6gb gtx1070 8gb

### ISSUE THREAD

**Issue by hamdyaea** [OhGodACompany/OhGodAnETHlargementPill#23]
Please make it works for gtx 1070 and 1060

**Comment by alltero** [comment]
Yes, it is necessary for 1060 !!

**Comment by Krassikn** [comment]
Yep. Do Cryptonight to reach the RX VEGA hashrates!

**Comment by jimmykl** [comment]
It's been clearly stated multiple times that this isn't happening and why but let me recount:

It is a memory timing based utility which only works on cards with GDDR5X memory i.e. 1080 and 1080ti. 

Memory intensive algos will see improvement, compute intensive, not so much.

**Comment by OhGodABird** [comment]
Thank you for the feedback, we take requests into account, but currently there are no short-term plans to prescribe treatment for other models.
