### ISSUE TITLE
open source the code

### ISSUE THREAD

**Issue by biskero** [OhGodACompany/OhGodAnETHlargementPill#25]
hello,

looks like is a great tool and free, so why not open source the code to the community?
It would be great.

**Comment by jimmykl** [comment]
It is a great tool! And it is free to the community! That is great twice. Why open source the code?

**Comment by biskero** [comment]
because open source software is always better from all point of view, security, improvements etc.
Most mining software are open source so this tool would be a great addition.

**Comment by OhGodABird** [comment]
The source contains code that can not be revealed in order to honor agreements. If you are interested in learning, I recommend you to check out other open-source tools provided by OhGodACompany.
