### ISSUE TITLE
1080TI / HiveOS / Equihash: 0-hash Improvement.

### ISSUE THREAD

**Issue by SolWax** [OhGodACompany/OhGodAnETHlargementPill#26]
I realize the name says "ETH" in it but, figured I would give it a try on Equihash (running HiveOS at the moment). 
Anyone else have same/different result on Equihash? Running a Linux/preconfigured m.o.s/windows? 
If you find an improvement please share results / fixes. 
Thanks!

**Comment by Yurexxx** [comment]
I've tested equihash miner on Linux Mint and got about 2-3% hashrate enlargement...

**Comment by OhGodABird** [comment]
Closing this thread as it's neither an issue, nor an active discussion.
