### ISSUE TITLE
1080: No difference in hash

### ISSUE THREAD

**Issue by nkyms** [OhGodACompany/OhGodAnETHlargementPill#30]
I have been successful in getting hash improvement with my 1080Ti's, but on my 1080 rigs I'm getting no difference in hash when running ETHlargementPill. I have revA on, as it crashes; probably an older card.
I've tried this on three seperate rigs, with multiple brands of 1080's. I've even isolated single cards and not one will work.

Any help would be appreciated.

**Comment by jimmykl** [comment]
Are you using OhGodAnETHlargementPill-r2? Running as an admin? On Windows or Linux? 

Any overclocking? Maybe try stock clocks first to make sure that's not causing any issues?

**Comment by nkyms** [comment]
I'm running r2 as admin on Windows 10.
I've tried without overclocking.

**Comment by OhGodABird** [comment]
There are not a lot of details about the issue, and it may not be relevant anymore, but in case it is, please start with the outline of how you run the pill just to make sure revA is used as prescribed.
If all else fails, the GPUs can be overclocked too for a test, but I would be surprised if that would be needed.

**Comment by OhGodABird** [comment]
The issue seems to be abandoned, therefore I'm closing it.
