### ISSUE TITLE
Hashrate?

### ISSUE THREAD

**Issue by Arinerron** [OhGodACompany/OhGodAnETHlargementPill#34]
Hey,

Do you think you could create a community-contributed table in the README file with the average hashrate for each card?

Specifically, I'm curious about the hashrate for a GTX 1080 (not Ti), but I would be curious to see the other cards too.

Thanks again.

**Comment by jimmykl** [comment]
Good idea. Maybe @OhGodABird or @OhGodAGirl could add a wiki page and allow anyone to edit it?

**Comment by newmzy** [comment]
Hi there - I have 2 MSI gtx1080 Gaming X cards. They both improved by approximately 10mh/s, now hashing at an average of 32-33 mh/s.

I hope that info is useful and you can add it to any README or wiki you want to.

**Comment by x53476** [comment]
I have the same MSI cards as newmzy and showing 32.0 - 32.2, or a +10 increase as well.
Interested in seeing what else we can do with these cards.

**Comment by OhGodAGirl** [comment]
Should be good now. GIve me your full model with a screenshot of your hashrate. I'll add it in with your username.

**Comment by jimmykl** [comment]
Woot! Thanks @OhGodAGirl 

EVGA GeForce GTX 1080 Ti SC Black Edition 

Overclocking: power limit 68% core +50 memory +450

![screen_shot_2018-04-29_at_3_33_13_pm](https://user-images.githubusercontent.com/113574/39402970-c8edb2f8-4bc2-11e8-8d7e-1fec8f9b37f8.jpg)

**Comment by jimmykl** [comment]
Also you can let anyone contribute to the wiki if you want https://help.github.com/articles/changing-access-permissions-for-wikis/ (Completely understand why that may not be useful…)

**Comment by gordan-bobic** [comment]
1080Ti: +150 GPU, +1500 VRAM, P2
Without: 37MH/s @ 150W
With: 54H/s @ 175W

**Comment by OhGodAGirl** [comment]
Cheers @jimmykl! I've opened it. It's fine, if users want to vandilize the wiki with pictures of dicks, well, I for one welcome our new dick overlords.

**Comment by jimmykl** [comment]
https://www.youtube.com/watch?v=9Wl_uQOABxg

**Comment by Tasselhoff** [comment]
With a PNY FE 1080 I'm getting ~21.4Mh/s stock with ~31.6Mh/s using the blue pill.

**Comment by OhGodABird** [comment]
Closing this thread as it's neither an issue, nor an active discussion, and the wiki already provides a good place for values.

**Comment by Arinerron** [comment]
@OhGodABird Yes, the wiki page was created as a result of this issue (so, this issue is resolved now): https://github.com/OhGodACompany/OhGodAnETHlargementPill/wiki/Hashrate-Results
