### ISSUE TITLE
other algos?

### ISSUE THREAD

**Issue by newmzy** [OhGodACompany/OhGodAnETHlargementPill#35]
First of all I must congratulate and thank you for solving my limpness problem with 2 1080s that I had decided were only good enough for gaming with. I will make a small contribution today sometime to one of your donation addresses.

This is not an "issue" as in problem, but a question.

Are you aware of anyone having success with the pill while mining any algorithms other than dagger-hashimoto? I guess it would be with any of the memory intense ones but I've never been sure exactly which ones benefit from memory overclocking (or "pilling") as much as dagger-hashimoto does.

I think that equihash seems to like a medium (like +400-500) memory overclock, and I also think neoscrypt does too.

I would like to do some experiments and report back the results but I don't want to interrupt the nicely engorged 1080s while they are making much more ETH for me than they used to.

Thanks again!

**Comment by B00gieman** [comment]
Sorry to ear that. I think the community Will not have any problem on devfee (1%). EQUIHASH pill should bem outstading. Hope you release it to the public. Thanks again for the eth pill.

**Comment by sound58** [comment]
@OhGodAGirl I'm sorry to see so much backlash on YouTube. Your team did a great job.

Do you require beta testers for the new miner release, or are there ways to help/become involved? Also, if EQUIlargement is going private/exclusive, will the "Vega"ra equivalent also be going that route? 

I've been mining from home for couple years while finishing grad school... but I have a few friends here in Canada who would like to expand our at home mining into a real farm. We currently have a warehouse picked out, and are on the edge of an investment decision. Always looking for ways to improve mining performance.

Thanks!

**Comment by OhGodAGirl** [comment]
We'll be thinking about something that the community can use. Until then, I'll be closing this issue unless someone else feels a need to re-open it.
