### ISSUE TITLE
Segfault on CentOS 7.x

### ISSUE THREAD

**Issue by gordan-bobic** [OhGodACompany/OhGodAnETHlargementPill#36]
Segfaults on startup.

Strace attached.

[OhGodAnETHlargementPill-r2.strace.txt](https://github.com/OhGodACompany/OhGodAnETHlargementPill/files/1957450/OhGodAnETHlargementPill-r2.strace.txt)

**Comment by pinkflozd** [comment]
i'm getting a segfault on Arch linux too
[trace.txt](https://github.com/OhGodACompany/OhGodAnETHlargementPill/files/1958504/trace.txt)

**Comment by eLvErDe** [comment]
Guys,

Try to boot with iomem=relaxed kernel parameter

**Comment by gordan-bobic** [comment]
I can confirm this resolves the segfault for me.

**Comment by pinkflozd** [comment]
resolved the problem on Arch linux too, working perfectly. Thanks
