### ISSUE TITLE
Is there any chance for the Pill reduce even more our pets lifespan?

### ISSUE THREAD

**Issue by xinxilas** [OhGodACompany/OhGodAnETHlargementPill#37]
As the title says:

Is there any chance for the Pill reduce even more our pets lifespan?

**Comment by jimmykl** [comment]
I've been keeping a close eye on my pets temperatures and haven't noticed any side effects or other signs of life shortening issues.

Of course you should make sure your pet gets plenty of fresh air (but avoid direct sunlight)

**Comment by xinxilas** [comment]
They are playing just like without the Pill

Im lay, but i believe that this has no side effects

**Comment by jimmykl** [comment]
Yeah I think it's safe too

**Comment by OhGodAGirl** [comment]
Dosing pets with pills can have significant side effects including: animal control seizing your pets; a court order; jail-time; sharing a bunk with Billy; and becoming Billy's wife. 

Dosing GPUs is okay, though.
