### ISSUE TITLE
My 1080 ti works max on 51mx

### ISSUE THREAD

**Issue by ma3atr0n** [OhGodACompany/OhGodAnETHlargementPill#38]
Good day!
I have issue with my 2 rigs on 1080Ti, first on EVGA WTF3 Hybrid and second on ZOTAC EXTREME EDITION, claymore last version.
I'm using HiveOS for mining and when i running "OhGodAnETHlargementPill" and restart miner i just have 51mx on both of rigs. Overclocking the memory do not have any effect on hashrate, my memory working on 11000.
Maybe i need to configurate miner or some other things?
![1080ti1](https://user-images.githubusercontent.com/38848459/39415243-ab1ad15c-4c49-11e8-9301-e69b674d1109.jpg)
![1080ti2](https://user-images.githubusercontent.com/38848459/39415244-ab3a2be2-4c49-11e8-9279-67be3456bced.jpg)
![1080ti3](https://user-images.githubusercontent.com/38848459/39415245-ab5821d8-4c49-11e8-96db-b9a912057d6a.jpg)

**Comment by jimmykl** [comment]
It looks like your cards are running in P2 power state/performance level. AFAIK they will overclock best at P0. Some background (Windows based but explains it well) http://cryptomining-blog.com/tag/nvidia-force-power-state/

I think you should investigate nvidia-smi on linux and see if you can remove the P2 setting default.

Possible leads for linux:
https://www.reddit.com/r/gpumining/comments/80dzzd/setting_p0_performance_level_in_linux/
https://bbs.archlinux.org/viewtopic.php?id=162960
https://devtalk.nvidia.com/default/topic/1010856/linux/how-to-force-performance-level-3-driver-381-22-with-gtx-1080-ti-/

Maybe some linux users could chime in if they know a sure fire way?

**Comment by gordan-bobic** [comment]
You cannot force P0 state in Linux, when the driver detects compute load it will go into P2 state. Adjust your OC to compensate, but bear in mind you need to do it in this order:
1) Start the compute process
2) Wait for hash rate return just to make sure
3) Apply OC, adjusted for the -1000 MHz P2 slowdown

When stopping:
1) Remove OC
2) Stop compute process

That will ensure your P2 OC settings that are effectively P0 +1000 settings don't crash the GPU when you stop the mining process.

Also, you don't need to restart the miner, you can start and stop the pill while the miner is running with the same effects.

**Comment by jimmykl** [comment]
Hi @ma3atr0n did @gordan-bobic's technique work for you?

**Comment by eLvErDe** [comment]
@gordan-bobic can you give us the nvidia-settings call you fire ? I've hard time understanding this relative clock offset stuff...

Thanks

**Comment by eLvErDe** [comment]
Thanks, at the moment I'm still how of luck. I'm trying to run nvidia-settings headless by temporary running it throughw xorg with a generated xorg.conf. I can send commands to all cards just fine but they fall into state P8 after xorg shutdown :/

**Comment by gordan-bobic** [comment]
This is unfortunately how Nvidia drivers and tools work on Linux. For any use of OC-ing you have to have Xorg running. As soon as Xorg shuts down, things will go into minimum power mode (P8) until Xorg starts up again. It's annoying as hell, but if you want to use OC-ing, there is currently no other way on Linux.

Having said that, considering that OhGodACompany guys have come with with this tool that adjusts memory timings on the fly, maybe we could try to persuade them to come up with a similar tool that also adjusts clock speeds on the fly without relying on Nvidia tools and thus Xorg.

**Comment by eLvErDe** [comment]
Mmhh, so it's worthless to keep trying to apply my settings without xorg running anymore ?
That's stupid but I can leave with a dummy xorg being started if it's really required.

Any chance you have memory and clock settings to bring back P0 state for 1080Ti and 1080 ?
Also if you have some o/c advice

Thanks a lot !

**Comment by gordan-bobic** [comment]
On Linux OC-ing _never_ worked without Xorg running.
The easiest way I have found is to configure the appropriate xorg.conf, and use the graphical default target:
```
systemctl set-default graphical.target
```
That will fire up Xorg and show a login prompt. But if you only ever use ssh to connect to the machine it won't matter. That's what I do.

On a 1080Ti you need +1000 on memory in P2 to get you back to the P0 baseline. All cards should handle this without problems, but make sure the card is in P2 _before_ you apply the OC, and reset offset back to 0 _before_ you stop the mining process or the GPU may crash.

I find that most of my 1080Ti cards can handle +1500 in P2 state, 24/7. I have one or two that are fully stable at +2000 (maximum settable), but it is rare to find a card that truly is stable at +2000 24/7, many will last a day or two before crashing, but this is not good enough as you'll just end up having to babysit the rigs.

I seem to recall 1080 cards are 1GHz lower on the default RAM clocks, but similar offsets should apply.

**Comment by eLvErDe** [comment]
What about core clock ?

Can you share you xorg.conf ? Does it fire up without a monitor being connected ? I'll share my stuff as soon as it's working

**Comment by gordan-bobic** [comment]
Something like this should work, assuming only 2 GPUs, extend as required:
```
Section "ServerLayout"
        Identifier      "Layout0"
        Screen          0 "Screen0" 0 0
        Screen          1 "Screen1" RightOf "Screen0"

        Option          "Xinerama" "0"
EndSection

Section "Device"
        Identifier      "Device0"
        Driver          "nvidia"
        VendorName      "NVIDIA Corporation"
        BoardName       "GeForce GTX 1080Ti"
        Option          "UseEDID" "false"
        Option          "AllowEmptyInitialConfiguration" "yes"
        Option          "ConnectToAcpid" "off"
        Option          "NoLogo" "1"
        Option          "Coolbits" "28"
        Option          "RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerDefaultAC=0x1"
        BusID           "PCI:7:0:0"
EndSection

Section "Device"
        Identifier      "Device1"
        Driver          "nvidia"
        VendorName      "NVIDIA Corporation"
        BoardName       "GeForce GTX 1080Ti"
        Option          "UseEDID" "false"
        Option          "AllowEmptyInitialConfiguration" "yes"
        Option          "ConnectToAcpid" "off"
        Option          "NoLogo" "1"
        Option          "Coolbits" "28"
        Option          "RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerDefaultAC=0x1"
        BusID           "PCI:8:0:0"
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "Unknown"
    HorizSync       28.0 - 33.0
    VertRefresh     43.0 - 72.0
    Option         "DPMS"
EndSection

Section "Monitor"
    Identifier     "Monitor1"
    VendorName     "Unknown"
    ModelName      "Unknown"
    HorizSync       28.0 - 33.0
    VertRefresh     43.0 - 72.0
    Option         "DPMS"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection

Section "Screen"
    Identifier     "Screen1"
    Device         "Device1"
    Monitor        "Monitor1"
    DefaultDepth    24
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection
```

If you want to maintain your sanity, make sure your devices' screen numbers are listed in the same order as the device IDs listed by nvidia-smi. You probably also want all your miners and related tools to start with this environment variable set:
```
CUDA_DEVICE_ORDER=PCI_BUS_ID
```

This will ensure that the CUDA device IDs are the same as the device IDs reported by nvidia-smi.

**Comment by eLvErDe** [comment]
Okay thanks, I'm already doing something like by iterating on nvidia-smi output.

Actually i'm thinking about spawning a simple flask based REST API in the dummy x session, so I could call stuff like GET /0/GPUMemoryTransferRateOffset[2] or POST /1/GPUMemoryTransferRateOffset[2]/1500 what you think ?

**Comment by eLvErDe** [comment]
@gordan-bobic 

I started a persistent Xorg servers, all cards are running in P2 state:

```
DISPLAY=:0.0 /usr/bin/nvidia-settings -tq '[gpu:1]/GPUCurrentClockFreqs' -tq '[gpu:2]/GPUCurrentClockFreqs' -tq '[gpu:3]/GPUCurrentClockFreqs' 

1645,5005
1645,5005
1645,5005
```

```
DISPLAY=:0.0 /usr/bin/nvidia-settings -a '[gpu:1]/GPUMemoryTransferRateOffset[2]=1500' -a '[gpu:2]/GPUMemoryTransferRateOffset[2]=1500' -a '[gpu:3]/GPUMemoryTransferRateOffset[2]=1500'

  Attribute 'GPUMemoryTransferRateOffset' (rig1.metz.levert:0[gpu:1]) assigned value 1500.
  Attribute 'GPUMemoryTransferRateOffset' (rig1.metz.levert:0[gpu:2]) assigned value 1500.
  Attribute 'GPUMemoryTransferRateOffset' (rig1.metz.levert:0[gpu:3]) assigned value 1500.
```

```
DISPLAY=:0.0 /usr/bin/nvidia-settings -tq '[gpu:1]/GPUCurrentClockFreqs' -tq '[gpu:2]/GPUCurrentClockFreqs' -tq '[gpu:3]/GPUCurrentClockFreqs'

1670,5005
1657,5005
1657,5005
```

Still unable to change memory clock, despite everything looks like working just fine, any hint ?

Thanks

**Comment by gordan-bobic** [comment]
Instead of
[gpu:1]/GPUMemoryTransferRateOffset[2]=1500
do
[gpu:1]/GPUMemoryTransferRateOffset[3]=1500

**Comment by eLvErDe** [comment]
Thanks a lot, here we go

```
DISPLAY=:0.0 /usr/bin/nvidia-settings -tq '[gpu:0]/GPUCurrentClockFreqs' -tq '[gpu:1]/GPUCurrentClockFreqs' -tq '[gpu:2]/GPUCurrentClockFreqs' -tq '[gpu:3]/GPUCurrentClockFreqs'

DISPLAY=:0.0 /usr/bin/nvidia-settings -a '[gpu:3]/GPUMemoryTransferRateOffset[3]=1370'
DISPLAY=:0.0 /usr/bin/nvidia-settings -a '[gpu:2]/GPUMemoryTransferRateOffset[3]=1520'
DISPLAY=:0.0 /usr/bin/nvidia-settings -a '[gpu:1]/GPUMemoryTransferRateOffset[3]=1550'
```

The regular 1080 aka gpu0 cannot stand any o/c, even 50 offset make it spits illegal instruction error in kernel log, weird.

With the pill being on:

```
ETH: GPU0 30.517 Mh/s, GPU1 54.471 Mh/s, GPU2 54.537 Mh/s, GPU3 53.791 Mh/s 
```

I fixed the memory clock value by doing F5 on Claymore's API, you can easily see the hashrate begining to drop when doing 10MHz offset step.

Thanks again for your help, I'm not sure it can be better but I'm open to any suggestion :)

A last question: is there anyway to "preload" the card in P2 state, so I can configure overclocking before running the miner ?

PS: nvidia-settings acutally provide --gpus to list gpu IDs, and --describe=all can be used to create all route with proper description and typing. I'll DEFINITELY turn this into an HTTP API, that would be awesome to monitor/configure nvidia cards on headless linux servers.

I'll update this ticket when I'll publish some code.

**Comment by gordan-bobic** [comment]
> A last question: is there anyway to "preload" the card in P2 state, so I can configure overclocking before running the miner ?

No, there isn't. The driver does it automatically and there is no official way to force a P state.

You should be aware that depending on the miner and intensity used, nvml calls can start to take a very long time and end up causing a rather high interrupt load. I particularly noticed this with excavator. Most other miners don't seem to suffer from this anywhere nearly as badly. So don't over-monitor. Once a minute is fine. Once/second is probably going to break something.

**Comment by DaReaLDeviL** [comment]
Is this also possible with gtx 1070 and the command
DISPLAY=:0.0 /usr/bin/nvidia-settings -a '[gpu:1]/GPUMemoryTransferRateOffset[3]=1550'
?

**Comment by jimmykl** [comment]
Hi @ma3atr0n I hope you OCs are stable and hashrates high! I'm on an issue cleanup rampage and wondered if you could close this issue?

I've added a link to it on the linux notes wiki page https://github.com/OhGodACompany/OhGodAnETHlargementPill/wiki/Linux-notes#overclocking to archive the good info from @gordan-bobic and @eLvErDe

**Comment by gordan-bobic** [comment]
Not the same thing.
