### ISSUE TITLE
For the record: Monero/XMR (CryptonightV7) peformance measurement

### ISSUE THREAD

**Issue by eLvErDe** [OhGodACompany/OhGodAnETHlargementPill#43]
Stock 1080Ti, PL 200W
Without: 773 With: 885: Improvment: 14%

Stock 1080, PL 120W:
Without: 535, With: 630: Improvment: 18%

Regards, Adam.

**Comment by OhGodAGirl** [comment]
Wonderful, thank you so much, @eLvErDe! Mind if I add this stuff to the Wiki?

**Comment by eLvErDe** [comment]
Absolutely

**Comment by gordan-bobic** [comment]
There's something wrong with the setup there. I'm seeing 1050 H/s on all my 1080Ti cards (variety of brands) with the pill, at 125W. The used to be around 850 H/s before.

**Comment by eLvErDe** [comment]
No there's nothing wrong. **STOCK**

**Comment by jimmykl** [comment]
Hey @eLvErDe I added those to the hashrate reports https://github.com/OhGodACompany/OhGodAnETHlargementPill/wiki/Hashrate-Results#cryptonight 
I'm on a github issue cleaning rampage so if you could close this that'd be cool 🙂
