### ISSUE TITLE
GTX 1080 FE: Program crashes, artifacts and/or reboots PC

### ISSUE THREAD

**Issue by BlackMoth88** [OhGodACompany/OhGodAnETHlargementPill#46]
**I was able to make the program work once and now I can't replicate it.**  To make it work, I ran the program through a command line in the shortcut (--revA) in administrator mode, and it crashed.  However, I ran it again and windows compatibility troubleshooter appeared.  I hit the "test this program" button and the command window appeared with the message.  I ran Phoenix miner and my card which used to reliably hash 26.3 mh/s with -400 core, +1000 mem was hitting over 38 mh/s.  That was amazing, and I didn't even think possible.  I ran the miner for approximately 4 hours with the hash rate increase remaining constant.

Unfortunately, after closing the program to do other things on my PC, it has not worked since.  I have tried a ton of things so far to get it to work, including running win8 compatibility mode through the shortcut as administrator.  I have gone back to stock clocks for all the testing.  I have tried running it through command prompt window and it crashes.  It does not usually crash if I don't apply "--revA," but just flashes the terminal box and does nothing.  Most of the time when I run it, the screen will artifact and crash, simply go black, or crash/restart.

I am running dual monitors (gaming PC, not on my mining rigs) and gsync.  I would adore the ETH boner.  10mh/s+ is an amazing gain through your glorious medication.

**Comment by Tasselhoff** [comment]
You're probably best starting with default settings rather than overclocking, as it is said to further stress the card (so existing stable OC may not work).

**Comment by 0Ne0** [comment]
Same issue here except I have never gotten it to work

**Comment by Tasselhoff** [comment]
It works fine for me. Here's my ethermine status (I had to stop a couple of times) but it seems pretty decent for a 1080 FE (PNY). What kind of share levels have you been getting without the "Pill"? I've only just started messing around with it so have no historical comparison.
![screenshot from 2018-05-05 01-43-25](https://user-images.githubusercontent.com/3210294/39657213-2b3ee5e8-5006-11e8-9cf6-21c3ef7ffeff.png)

**Comment by 0Ne0** [comment]
Mines a straight founders eddition from nvidia. Not PNY

**Comment by seanmpage** [comment]
I'm also having the same issues with nvidia brand 1080fe.

**Comment by Rastishka-Power** [comment]
Same issue there. Have 5 of 1080FE. After applying the "pill" - crash+restart.

Found the solution for me - start mining software(claymore 11.5), after DAG generation and mining is began, apply the Pill - works fine 34.8Mh per card.

Also, if pool closes connection and mining is stopped - system has crushed\restarted. So i'm using windows scheduler to start mining and after 5 min - the Pill

**Comment by BlackMoth88** [comment]
Rastishka-Power, that worked!  I started Phoenix Miner, let DAG generation finish and then right clicked on the program shortcut and clicked "troubleshoot compatibility."  From there, I hit the "try recommended settings" button and that did it.  Image below:

![capture2](https://user-images.githubusercontent.com/38897738/39674680-0e7d8238-5115-11e8-8169-e9150a1baaf5.JPG)

**Comment by viabtckevin07** [comment]
2018/5/6 23:05於 "BlackMoth88" <notifications@github.com>寫道：
>
> Rastishka-Power, that worked! I started Phoenix Miner, let DAG generation
finish and then right clicked on the program shortcut and clicked
"troubleshoot compatibility." From there, I hit the "try recommended
settings" button and that did it. Image below:

**Comment by 0sm3l** [comment]
Same issue with a Zotac 1080 :(

**Comment by OhGodABird** [comment]
Although the mentioned workaround shouldn't be really needed, it's likely one of the many hard to explain Windows only issues.
While the pill can theoretically cause crashes on rare occasions, almost guaranteed crashes on usage spikes like starting or stopping mining is almost always the sign of too high clocks for the specific GPU (and occasionally PSU).
As there's no remaining issue that can be fixed in the pill, I'm closing this thread.
