### ISSUE TITLE
Holy fuckballs

### ISSUE THREAD

**Issue by jimmykl** [OhGodACompany/OhGodAnETHlargementPill#5]
<img width="836" alt="screen shot 2018-04-23 at 5 54 23 pm" src="https://user-images.githubusercontent.com/113574/39109075-69fb33bc-471f-11e8-9f49-e704ea652b67.png">

**Comment by jimmykl** [comment]
Though poolside currently showing 205 so let's wait and see how long this pill lasts to make sure it's not a placebo…

**Comment by jimmykl** [comment]
5x 1080ti stable @ 262 poolside. Goddam. Where do I signup for the full version for my 1070s or should I be listing them to sell and move to all 1080ti?

**Comment by tonymorella** [comment]
![screenshot at 2018-04-23 20-32-11](https://user-images.githubusercontent.com/3123270/39125066-bf01f3b4-4738-11e8-878f-821497f2fed3.png)

This is running at 175 Watts, had to limit because of the PSU's I am running on but still, fuckballs indeed :()

**Comment by OhGodAGirl** [comment]
@jimmykl We are very happy that ETHlargement made your hashrate harden. Did you encounter any issues on a 1080? Was the --revA flag easy to use?

**Comment by jimmykl** [comment]
@OhGodAGirl No issues with ETHlargement itself on 5x 1080ti. 

The --revA flag was easy enough to use, though the name is a bit obscure.

I did notice severe lag with MSI Afterburner. I know I should be using nvidiaInspector or NVSMI but prefer fan curve control vs constant speed. Is there a chance that whatever ingredients are in the magic pill cause an allergic reaction with tools like Afterburner?

**Comment by nvmax** [comment]
Ok question?  I have tested this out and running 2x GTX 1080Ti's at 38.4Mh/sec averaging 34 Shares per hour over, been running this way for months, havent changed from that, the 10 hours previously to this I averaged 34 shares then I turned on this tool and let it go for 10 hours and came up with 33 shares average over 10 hours.

Now, I went from 38.4 MH/sec to 55.6 Mh/sec and yet the shares have not increased to the same % as the hashing,  Also on nanopool it shows it jumped up and reporting now 111.2 Mh/sec yet my SMA average is still that of when my cards were at 38.4 Mh/sec the shares per hour have effectively stayed the exact same granted 1 share less average then the previous 10 hours.

Now if it was running and working and showing 55Mh/sec then why is it only performing that of what it was getting at 38.4Mh/sec it effectively hasnt done anything, can you explain this ?
