### ISSUE TITLE
X16R Mining

### ISSUE THREAD

**Issue by sound58** [OhGodACompany/OhGodAnETHlargementPill#50]
Anyone apply this to Ravencoin? Wondering if the pill would improve performance of some of the algos as it swaps around.... Not all, but some.

**Comment by tbates76** [comment]
@sound58 its only for ETH

**Comment by drinkability** [comment]
testing it now looks promising

**Comment by drinkability** [comment]
eth enhancement stabilizes hash rates no 52-22 back and forth I get around 30 and between 6-8 raven an hr at .047 a raven I make 6.30 a day with a auros 1080 ti and a founders edition original still testing my overclocks but doing 150 core 500 standard plus 4 on core power 85 limit on  they are fickle they like the power less than 80 not stable for more than 8 hrs

**Comment by drinkability** [comment]
correction 7 a day .047 raven 6.25 an hr

**Comment by drinkability** [comment]
my opinion it helps stabilize the 16r cause of the bios  going 2 start testing on other my other rigs one at a time see if it likes more gpus and different motherboards this one is a 775 motherboard quad 6600 g0 stepping 2.4 overclocked 2 3.4 watercooled my first build 10 yrs ago still working like a champ I test new risers everthing on this before hooking it up 2 my newer builds if it don't work on this its no good and my personal 5 mining machines and what I build for my buds have never failed

**Comment by sound58** [comment]
@drinkability Thanks for trying this. Those are nice numbers if it can run stable. 

I'm not knowledgeable enough to know how this works. My understanding is that it adjusts the memory clock; thus improves memory based algos like Ethash but has no effect on Equihash. 

X16R swaps between 16 different algos... so the Pill might improve a couple of them.

0=​blake 1=bmw 2=groestl 3=jh 4=keccak 5=skein 6=luffa 7=cubehash 
8=shavite 9=simd A=echo B=hamsi C=fugue D=shabal E=whirlpool F=sha51 

I need to do more reading.

@tbates76 Thanks for the dumb lazy reply.

**Comment by tbates76** [comment]
@sound58 from my understanding it takes the memory timings and adjusts them for the 1080 cards. That being said a miner using this on x16 would have their system crash once it switched to a non mem algo.  Have fun with this. Hope ya get it to work

**Comment by OhGodABird** [comment]
Closing this thread as it's neither an issue, nor an active discussion, and the wiki already provides a good place for hashrate comparisons.
