### ISSUE TITLE
Just a note  980ti nvidia plz some day bring up to its real hash rate.

### ISSUE THREAD

**Issue by auroracoin** [OhGodACompany/OhGodAnETHlargementPill#52]
980ti nvidia plz someday do a fix bring up to its real hash rate.  thx

**Comment by Dagamus138** [comment]
Kristy mentioned in a youtube video that there is a paid version for older GeForce cards. 

The question of price was brought up and she said it is a matter of whether or not you are a jerk or act nice (paraphrasing). I would love to get my 980Tis and 780Tis hashing on some ETH. With the ZEC ASIC announced for release today the Maxwell cards will be pretty much worthless for mining without it. The 780Tis are worthless for mining but could run some of the less intensive memory algos on DaggerHashimoto.

I've searched a little, nothing serious as I always get distracted by other mining conversations and builds. But I cannot find anything related to a paid version. Maybe it is just a word of mouth thing.

**Comment by OhGodAGirl** [comment]
Paid versions are done on a case-by-case basis. Just like private miners, we only sell to certain individuals.

We're trying to launch a devfee version, soon, but May 25th's launch has us preoccupied. 

The 980 and 780 are really, really old; we'll look into this for the devfee version.

**Comment by xbkingx** [comment]
> Paid versions are done on a **case-by-case basis**. Just like private miners, we only sell to **certain individuals**.

I am _certain_ I would like a _case_ of pills. Wakka wakka! Ohgodthepricejusttripled...

But, seriously, awesome of you guys to release this for free. Thanks much.

**Comment by auroracoin** [comment]
Yes I wonder how much the cost would be for someone who has 2x 970..2x 980ti a 1x 1070. And I literally mine for my medical bills. I have disabilities hence I'm disabled. :-)

**Comment by jimmykl** [comment]
Hey guys I'm in the same boat, I'd love a pill for my 1060 and 1070 rigs, but I suspect @OhGodAGirl and co are super busy with mineority.io for the foreseeable future.

I'm sure if a pill is released for other cards you'll hear about it! But in the meantime @auroracoin could you close this issue?

**Comment by Angel996** [comment]
I got a bunch of 780s, 970s, 980s, 1060s. If you make a devfee version, I'd love to have it. Ubuntu 16.04 LTS. Please. ))

**Comment by michstuff** [comment]
Still no news?

**Comment by auroracoin** [comment]
No. :(   @michstuff
