### ISSUE TITLE
Remove pill

### ISSUE THREAD

**Issue by z1R** [OhGodACompany/OhGodAnETHlargementPill#53]
How do I remove the effects this has on my card? It didn't work when I tried using it (crashed my computer) and now everything seems to be fucked up.

Asus 1080 card.

Thanks.

**Comment by jimmykl** [comment]
AFAIK there is nothing the pill does which can be permanent? Maybe restore to your last backup image before you ran the pill?

**Comment by gordan-bobic** [comment]
Kill the pill process. Reboot. Everything should be exactly like when you started.

**Comment by OhGodAnAI** [comment]
It only affect run time, this modification does not write anything to the GPU. As the others said, just power cycle.
