### ISSUE TITLE
GTX-1050TI - 1060 3/6 GB - 1070-TI doesn't work..

### ISSUE THREAD

**Issue by perons88** [OhGodACompany/OhGodAnETHlargementPill#56]
Hi when you can add that type of gpu?? or if u don't want to code for free.. how much you want?

**Comment by OhGodAnAI** [comment]
It is not supported. You are welcome to email us and ask for a quote, make sure to include how many GPUs and what model you are running.

**Comment by perons88** [comment]
i run 2 gtx 1060 3 gb zotac single fan , on windows 7.. 6 gtx 1060 3 gb zotac on ethos, 3 gtx 1050ti on ethos, and the last one gtx 1060 3 gb zotac on windows 7

**Comment by OhGodAnAI** [comment]
Please use intended method of communication, this is not a forum. Thank you.
