### ISSUE TITLE
1060's? - Anything in the Works?

### ISSUE THREAD

**Issue by TerpFan** [OhGodACompany/OhGodAnETHlargementPill#57]
Hi guys,

Anything in the works to help the GTX 1060's?  I don't mind paying for it.

**Comment by nkyms** [comment]
Would be very interested in this too.

**Comment by tech3ric** [comment]
interested here too..

**Comment by whotheff** [comment]
Can this pill be modified to overcome the Hynix memory controller limitation, which prevents the controller to reach 100% load?

**Comment by kolet** [comment]
@TerpFan  @nkyms  @tech3ric  @whotheff 
they do have a "PILL" for older nvidia cards but not for the public at the moment.

they are selling this technologie for companies and there is not a fix price. (i am pretty sure u if u are not a farm u wont be able to afford it.)

**Comment by DmitryDMR** [comment]
Can this pill be modified to GTX 1060 6Gb 9Gbps with DDR5X ?

**Comment by jimmykl** [comment]
Hey guys I'm in the same boat, I'd love a pill for my 1060 and 1070 rigs, but I suspect @OhGodAGirl and co are super busy with mineority.io for the foreseeable future.

I'm sure if a pill is released for other cards you'll hear about it! But in the meantime @TerpFan could you close this issue?
