### ISSUE TITLE
1070

### ISSUE THREAD

**Issue by thesrdjan** [OhGodACompany/OhGodAnETHlargementPill#58]
Hi guys,

Anything in the works to help the GTX 1070's?

**Comment by kolet** [comment]
@thesrdjan 

they do have a "PILL" for older nvidia cards but not for the public at the moment.

they are selling this technologie for companies and there is not a fix price. (i am pretty sure u if u are not a farm u wont be able to afford it.)

**Comment by thesrdjan** [comment]
Do you know who i can contact for more information?tnx in advance...

**Comment by kolet** [comment]
yes, via @OhGodAGirl  email look into her github

**Comment by williamford12** [comment]
You can contact them at twitter: https://twitter.com/OhGodACompany

**Comment by jimmykl** [comment]
Hey guys I'm in the same boat, I'd love a pill for my 1060 and 1070 rigs, but I suspect @OhGodAGirl and co are super busy with mineority.io for the foreseeable future.

I'm sure if a pill is released for other cards you'll hear about it! But in the meantime @thesrdjan could you close this issue?
