### ISSUE TITLE
backup original rom

### ISSUE THREAD

**Issue by logicminds** [OhGodACompany/OhGodAnETHlargementPill#59]
I assume the pill changes something on the vbios.  Can we back this up first?  How do we backup just in case?

**Comment by jimmykl** [comment]
From all reports the pull is temporary and although it's interacting with the vbios at some level it does nothing permanent. Of course you can still back up a vbios [this way](http://nvidia.custhelp.com/app/answers/detail/a_id/4188/~/extracting-the-geforce-video-bios-rom-file)

**Comment by logicminds** [comment]
Great, tried it out. Have no idea what it does but a reboot is only need to bring back to original state.
