### ISSUE TITLE
How to background OhGodAnETHlargementPill-r2 for LINUX Systemd service

### ISSUE THREAD

**Issue by fireheadman** [OhGodACompany/OhGodAnETHlargementPill#60]
Love the tool!!
have been attempting to put this into an autostart systemd service (script) that will launch in background on reboot.  Cannot see to get this to work.

For now having to launch it separately with "&".

**Comment by eLvErDe** [comment]
https://github.com/OhGodACompany/OhGodAnETHlargementPill/wiki/Linux-notes#hiveos-install

**Comment by OhGodABird** [comment]
Closing this thread as it's neither an issue, nor an active discussion, and the wiki already provides a good place for such notes.
