### ISSUE TITLE
gtx 1080

### ISSUE THREAD

**Issue by coolxraygun** [OhGodACompany/OhGodAnETHlargementPill#64]
hello
i have an gtx 1080 strix and i am wondering what is the best oc settings i can only get my card to 34-35 MH and whould you get beter performance on linux?

**Comment by jimmykl** [comment]
Hi @coolxraygun

Those are good numbers from a 1080. I've added them to the hashrate results list https://github.com/OhGodACompany/OhGodAnETHlargementPill/wiki/Hashrate-Results where you can compare.

I can't comment on linux but from what I've heard I doubt you'd get much more out of them. Of course you wouldn't have to deal with Defender and random updates 😉

**Comment by Tasselhoff** [comment]
I should have replied here instead of creating a new issue (https://github.com/OhGodACompany/OhGodAnETHlargementPill/issues/75)

**Comment by Tasselhoff** [comment]
I just tested my card using those settings at ethermine for a few hours. 
Reported hashrate 36.6 MH/s 
Current 45.9 MH/s
Average 32.7 MH/s
![screenshot of 1080 for a few hours](https://user-images.githubusercontent.com/3210294/41799993-df12cf9c-7673-11e8-9815-f1a111bd58b9.png)

**Comment by Tasselhoff** [comment]
I've pushed my overclocking to +2000 (with fan at 86%) and am getting >=38.5Mh/s on my 1080. I'm not sure this would be wise on a non-FE card.

**Comment by OhGodABird** [comment]
Closing this thread as it's neither an issue, nor an active discussion, and the wiki already provides a good place for hashrate comparisons.
