### ISSUE TITLE
SMOS wiki update

### ISSUE THREAD

**Issue by jarislv** [OhGodACompany/OhGodAnETHlargementPill#65]
Hi,

Just want to help update wiki, current posted code won't work to run OhGodAnETHlargementPill at the background for SMOS anymore. With their recent update, OhGodAnETHlargementPill is located at 'utils' library.

current code:
`sudo /home/miner/OhGodAnETHlargementPill-r2 &`

new code:
`sudo /root/utils/OhGodAnETHlargementPill &`

**Comment by jimmykl** [comment]
Awesome thanks @jarislv I've updated that now (it is a wiki so you can edit too 😉)

**Comment by OhGodABird** [comment]
Thank you for the update.
