### ISSUE TITLE
how to setup and run OhGodAnETHlargementPill on ethos ( linux)

### ISSUE THREAD

**Issue by q8miner** [OhGodACompany/OhGodAnETHlargementPill#69]
I need to know the steps on
how to setup and run OhGodAnETHlargementPill on ethos ( linux)
thanks

**Comment by iamniks** [comment]
Hey. You can run this in your terminal:
`bash <(curl -s http://update.ethosdistro.com/packages/hotfixes/1080hashup.sh)`

**Comment by VoonzHub** [comment]
iamniks => you've juste made my day !
Thanks

**Comment by jimmykl** [comment]
Nice @iamniks I've added that to the Linux notes in the wiki

@q8miner if that answers your question could you close the issue? 🙂

**Comment by q8miner** [comment]
Thanks
