### ISSUE TITLE
Overclocking app compatibility / windoze

### ISSUE THREAD

**Issue by jimmykl** [OhGodACompany/OhGodAnETHlargementPill#7]
My test rig has a windoze 10 infection and, even worse, is addicted to MSI Afterburner (for fan curves). Running ETHlargement has made them veeeery laggy, far more than usual.

Is there a chance that whatever ingredients are in the magic pill cause an allergic reaction with Afterburner? Maybe it's fandangled checkboxes like 'Enable low-level IO driver' and 'Enable low-level hardware access interface: user mode/kernel mode'?

**Comment by justchil** [comment]
@jimmykl  I am not having any issues with the pill and AB.  Are you using Claymore 11.7 by chance?  I have run into some issues with AB + 11.7 while testing the new fan/temp/clock switches added to this version (on a rig not using this software).

I only have my main work station with a GPU that works with this but I can say it works flawless with AB 4.4.2 + 391.01 driver + Claymore 11.6.

**Comment by jimmykl** [comment]
Thanks @justchil I was using Claymore 11.7 and then moved to PhoenixMiner to see if that made a difference (it didn't). My test rig is a bit of a mutant so I'm going to keep it simple, re-image it and see how it fares then – will try 11.6 to begin with too.

**Comment by justchil** [comment]
If you tried / are using the new -tt -fanmin -fanmax etc... you will have to DDU + reinstall the video driver.  I also deleted the AB profiles.
