### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by BobbyGR** [OhGodACompany/OhGodAnETHlargementPill#70]
Windows Defender is starting to snag the pill, even in excluded folders they are snagging it.  these latest updates from Defender are getting a bit crazy.

**Comment by jimmykl** [comment]
Those crazy cats at Microsoft, give this a whirl https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-defender-antivirus

**Comment by AZ-Ronin** [comment]
As BobbyGR said, even in excluded directories... the --revA commands no longer work because the 3.exe file isn't run in the same directory. Any other suggestions? It won't let me remove it from quarantine either...

**Comment by AZ-Ronin** [comment]
I've reinstalled Windows and still no joy after downloading the app again. It work with my Ti's but not with my 1080's. It no longer pulls up it's own window either.

**Comment by AZ-Ronin** [comment]
Any suggestions or solutions would be appreciated. I've lost about 6.7Mh/s to this problem and that adds up. Thanks!

**Comment by AZ-Ronin** [comment]
I went ahead and removed the --revA from the command string and now my 1080's are running at full speed once again. Whatever the update was to Windows (or drivers) removed the need for it.

**Comment by OhGodABird** [comment]
We can't control what "anti"-viruses do, therefore it's up to the administrator of the system to ensure that one misbehaving program isn't affecting others negatively.
While I don't endorse this solution, Windows Defender can be totally disabled, which may be unfortunately the only way to stop it from interfering, as it's known not to respect its settings.

Obviously the Linux flavor of the pill isn't affected, using that is another way to solve this issue.
