### ISSUE TITLE
Changing algos problem

### ISSUE THREAD

**Issue by xinxilas** [OhGodACompany/OhGodAnETHlargementPill#71]
While using my "stable" OC Profiles, with +700 mem clock(1080)
I have troubles to stop mining(for example to switching algo mining purposes), or change memory clock while mining, or simply closing miner, or closing ETHPill exe
Right after doing any of this examples, artifacts appears on screen, and than reboots..
(it doesnt happens if i dony use the Pill)

Is there any way to fix it?
Its very important to switching mining algos here, or ill be stuck to mine always Eth...
It would be  perfect if i fix it

I'm able to fix that using less memory clock, but it drops all my hash-rates,

Same issue using 1080 ti, i cant use the same mem / clock overclock i use when mining Lyra2Rev2 if the pill is running...
I.E:
Nicehash running  lyra2rev2, then DaggerHashimoto became more proftiable, nicehash stops mining lyra2rev2,  PC will freeze and mem/clocks/pl will reset, or PC will reset, sometimes it can start to mine DaggerHashmoto but it freezes then too...

**Comment by Rudash** [comment]
The same issue as above. Freezes appears after a change of algos.

**Comment by OhGodABird** [comment]
Did you try it without overclocking the memory?
Do note that the pill is letting the GPU use its resources more efficiently, but as there's more work to do this way, the increased load can easily make previously working OC settings unstable.
If it's working without overclocking, then please report back, and try to use a milder OC.

**Comment by OhGodABird** [comment]
The issue seems to be abandoned, therefore I'm closing it.
