### ISSUE TITLE
Artifacts on GTX 1080 even after rebooting and uninstalling display drivers

### ISSUE THREAD

**Issue by arana1014** [OhGodACompany/OhGodAnETHlargementPill#73]
I tried this program and it immediately made my cards have artifacts on them. I rebooted and the issue still persists. What worse is that the integrated graphics are also affected. Artifacts are so bad I'm getting a green screen with the integrated graphics, just a few red dots with the GTX 1080s
I had both internal and external graphics enabled when I ran the program.

Is there any way to revert the changes?

**Comment by jimmykl** [comment]
Restart the rig. Don't run the pill again. Job done.

**Comment by arana1014** [comment]
I tried that already, did not work, I even deleted the pill file.

**Comment by jimmykl** [comment]
In that case afaik it can't be the pill. Have you removed all overclocking?

**Comment by arana1014** [comment]
I removed all overclocking already, artifacts are so bad sometimes the whole screen flickers

**Comment by OhGodABird** [comment]
The pill doesn't store persistent information and its modification can disappear several ways, including the mentioned reboot, but power cycling is the absolutely sure way to have no residual effects.
As overclocking was implied in the conversation, I think the issue should be looked for in the overclocking software.
