### ISSUE TITLE
EVGA 1080 FTW Low Hash

### ISSUE THREAD

**Issue by aidonaks** [OhGodACompany/OhGodAnETHlargementPill#76]
Hi,

Thanks for this free tool, it works great on my 1080 Ti cards! Unfortunately, not so well on my 1080 running on the same rig. So this post is just in case there's some improvement for 1080's possible in future versions.

I'm getting 25.7 MH/s on my eVGA 1080 FTW using RevA and OhGodAnETHlargementPill-r2. The rig reboots within seconds without RevA but is stable with it.

Settings: Core 1531 @ 900mv, Mem 10010 Mhz, 65% power limit. The "force P2 state" setting is turned off using Nvidiaprofileinspector. I tried stock settings and various others but it's pretty much the same. The best I can get is at 27 MH/s at 10400 Mhz mem so I preferred to keep memory at 10000. 

This is on Windows 10 64 bit, running as admin, nvidia driver 384.94. Using bios version 86.04.3B.01.82  - attached.
[1080ftwbackup.zip](https://github.com/OhGodACompany/OhGodAnETHlargementPill/files/2129585/1080ftwbackup.zip)

**Comment by Tasselhoff** [comment]
Mem 5005 Mhz? Isn't that really low? I'm using P2 (10526MHz)+1500 and getting 36.6MH/s (with GPU max clock at 1911MHz -200) for a 1080.

**Comment by aidonaks** [comment]
Said 5005 cause that's what it shows on Afterburner, that's actually 10010 Mhz.

**Comment by OhGodABird** [comment]
Have you tried running it without overclocking first? The power limit is generally safe to keep, but modifying clocks without establishing a stable reference first is the majority of the issues users face.

**Comment by OhGodABird** [comment]
The issue seems to be abandoned, therefore I'm closing it.
