### ISSUE TITLE
how to set memory 5994/5998 in Ethos for 8GPU Rig

### ISSUE THREAD

**Issue by q8miner** [OhGodACompany/OhGodAnETHlargementPill#78]
Hi,
Need your help with OhGodAnETHlargementPill memory setting

In the ETHlargementPill Interview with Developer - OhGodAGirl
she mentioned to set  the memory to 5994/5998
I was able to set it for 1 GPU rig as I put "globalmem 5994" in local.conf

but I cant do it for 8 GPU rig 

it gives error "Miner cannot initialize for 5 minutes, need to restart miner!"

NVIDIA Cards available: 8 
CUDA Driver Version/Runtime Version: 9.0/8.0
GPU #0: GeForce GTX 1080 Ti, 11172 MB available, 28 compute units, capability: 6.1  (pci bus 1:0:0)
GPU #1: GeForce GTX 1080 Ti, 11172 MB available, 28 compute units, capability: 6.1  (pci bus 2:0:0)
GPU #2: GeForce GTX 1080 Ti, 11172 MB available, 28 compute units, capability: 6.1  (pci bus 3:0:0)
GPU #3: GeForce GTX 1080 Ti, 11172 MB available, 28 compute units, capability: 6.1  (pci bus 7:0:0)
GPU #4: GeForce GTX 1080 Ti, 11172 MB available, 28 compute units, capability: 6.1  (pci bus 13:0:0)
GPU #5: GeForce GTX 1080 Ti, 11172 MB available, 28 compute units, capability: 6.1  (pci bus 14:0:0)
GPU #6: GeForce GTX 1080 Ti, 11172 MB available, 28 compute units, capability: 6.1  (pci bus 15:0:0)
GPU #7: GeForce GTX 1080 Ti, 11172 MB available, 28 compute units, capability: 6.1  (pci bus 16:0:0)
Total cards: 8 
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssMiner cannot initialize for 5 minutes, need to restart miner!
ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssMiner cannot initialize for 5 minutes, need to restart miner!
sssssssssssssssssssss

**Comment by q8miner** [comment]
solved 
globalmem 5800
globalcore -200

if not work for you start to lower globalmem by 50 and try each time, so start with 5750 and then 5700 till it work

**Comment by OhGodABird** [comment]
The result of overclocking is always dependent on the specific hardware it's applied to, therefore it's always the user's responsibility to find the right values. Values mentioned may be either exceptional or working for the majority, but the minimum delta is always zero, because overclocking is never guaranteed to work at all.
