### ISSUE TITLE
Segmentation fault on Linux

### ISSUE THREAD

**Issue by eLvErDe** [OhGodACompany/OhGodAnETHlargementPill#8]
Hi there,

Would have been happy to give a try but sadly it crashes on my Linux box:

Here is its last moment captured by strace:

```
[pid  1992] close(5)                    = 0
[pid  1992] getdents(4, /* 0 entries */, 32768) = 0
[pid  1992] close(4)                    = 0
[pid  1992] open("/sys/bus/pci/devices/0000:00:02.0/config", O_RDONLY) = 4
[pid  1992] pread64(4, "\0", 1, 14)     = 1
[pid  1992] close(4)                    = 0
[pid  1992] open("/sys/bus/pci/devices/0000:03:00.0/config", O_RDONLY) = 4
[pid  1992] pread64(4, "\200", 1, 14)   = 1
[pid  1992] mmap(NULL, 16777216, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0xf2000000) = -1 EPERM (Operation not permitted)
[pid  1992] close(4)                    = 0
[pid  1992] open("/sys/bus/pci/devices/0000:04:00.0/config", O_RDONLY) = 4
[pid  1992] pread64(4, "\200", 1, 14)   = 1
[pid  1992] mmap(NULL, 16777216, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0xd2000000) = -1 EPERM (Operation not permitted)
[pid  1992] close(4)                    = 0
[pid  1992] open("/sys/bus/pci/devices/0000:05:00.0/config", O_RDONLY) = 4
[pid  1992] pread64(4, "\200", 1, 14)   = 1
[pid  1992] mmap(NULL, 16777216, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0xb2000000) = -1 EPERM (Operation not permitted)
[pid  1992] close(4)                    = 0
[pid  1992] open("/sys/bus/pci/devices/0000:06:00.0/config", O_RDONLY) = 4
[pid  1992] pread64(4, "\200", 1, 14)   = 1
[pid  1992] mmap(NULL, 16777216, PROT_READ|PROT_WRITE, MAP_SHARED, 3, 0x92000000) = -1 EPERM (Operation not permitted)
[pid  1992] close(4)                    = 0
[pid  1992] mprotect(0x7ff4ca19b000, 1048576, PROT_READ) = 0
[pid  1992] rt_sigreturn({mask=[]})     = 140689339428864
[pid  1992] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x7ff4ca19b000} ---
[pid  1992] mprotect(0x7ff4ca179000, 131072, PROT_READ) = 0
[pid  1992] mprotect(0x7ff4ca19b000, 1048576, PROT_READ|PROT_WRITE) = 0
[pid  1992] rt_sigreturn({mask=[]})     = 140689339428864
[pid  1992] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x7ff4ca179000} ---
[pid  1992] mprotect(0x7ff4ca179000, 131072, PROT_READ|PROT_WRITE) = 0
[pid  1992] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x9a029b} ---
[pid  1990] <... futex resumed>)        = ?
[pid  1992] +++ killed by SIGSEGV +++
+++ killed by SIGSEGV +++
Segmentation fault
```

As I understand you want to keep the code private, I'd be happy to help in private for testing and/or running gdb against a not stripped binary

Thanks anyway,

Adam.

**Comment by eLvErDe** [comment]
Btw, it has 3 new 1080Ti and one old 1080, so maybe I mis-used the --revA flag ?

**Comment by eLvErDe** [comment]
r2 still crashing

**Comment by OhGodABird** [comment]
As shown by the strace output, access to the GPUs are rejected with "-1 EPERM (Operation not permitted)". The values seem to be fine, therefore the issue is likely running the program without privileges it needs. Have you tried running it as root?

**Comment by OhGodAGirl** [comment]
I just have to ask...why are you running a NVIDIA-only tool on a box with no NVIDIA cards? What does that accomplish?

**Comment by eLvErDe** [comment]
Yes it was running as root, so thats probably a kernel protection, I'll try to figure out and let you know if I found something.
I recall a kernel parameter I had to use one to enable raw access to GPIO through mem, that could definitely help. iomem=relaxed if I remember correctly.

@OhGodAGirl this my primary dev box, despite it has no Nvidia card I use it for most of my CUDA related builds, so I wanted to make sure it was related to the access of an actual Nvidia card

**Comment by eLvErDe** [comment]
That was a good catch:

```
ETH: 04/26/18-08:05:43 - New job from eu1.ethermine.org:4444
ETH - Total Speed: 115.054 Mh/s, Total Shares: 3, Rejected: 0, Time: 00:01
ETH: GPU0 20.734 Mh/s, GPU1 31.440 Mh/s, GPU2 31.451 Mh/s, GPU3 31.429 Mh/s
ETH: 04/26/18-08:05:45 - New job from eu1.ethermine.org:4444
ETH - Total Speed: 114.943 Mh/s, Total Shares: 3, Rejected: 0, Time: 00:01
ETH: GPU0 20.734 Mh/s, GPU1 31.381 Mh/s, GPU2 31.414 Mh/s, GPU3 31.414 Mh/s
```

```
ETH: 04/26/18-08:09:19 - New job from eu1.ethermine.org:4444
ETH - Total Speed: 169.301 Mh/s, Total Shares: 6, Rejected: 0, Time: 00:02
ETH: GPU0 30.551 Mh/s, GPU1 46.894 Mh/s, GPU2 44.955 Mh/s, GPU3 46.902 Mh/s
ETH: 04/26/18-08:09:19 - New job from eu1.ethermine.org:4444
ETH - Total Speed: 169.301 Mh/s, Total Shares: 6, Rejected: 0, Time: 00:02
ETH: GPU0 30.551 Mh/s, GPU1 46.894 Mh/s, GPU2 44.955 Mh/s, GPU3 46.902 Mh/s
```

Thanks :-)

What I did:

1. Add iomem=relaxed to GRUB_CMDLINE_LINUX_DEFAULT in /etc/default/grub
2. update-grub
3. reboot

Do you consider handling EPERM correctly ? If so I'd be happy to do a before/after check to confirm your error handling is working fine.

**Comment by OhGodABird** [comment]
Your kernel was likely compiled with the option CONFIG_IO_STRICT_DEVMEM which is uncommon in distributions commonly used for mining, and that causes the pill to successfully pass the root check but fail later.

There are currently no short-term plans for another release, but I added a note to have mmap error handling in the public version too.

Thank you for the information.

**Comment by eLvErDe** [comment]
Yep, you'll probably get more feedbacks like this because it's default configuration for Debian kernels. It's means everything based on Ubuntu will have the same behavior for sure, maybe not at the moment but when Ubuntu Bionic will be released it will ;-)

**Comment by Aminuxer** [comment]
I had confirm this issue.
I try this tool at Fedora-25_x64 with some 1080-Ti cards and see same error:
# ./OhGodAnETHlargementPill-r2
+----------------------------------------------------------------------------+
|                  OhGodAnETHlargementPill by OhGodACompany                  |
|            Public Edition Limited to 1080, 1080 Ti and Titan Xp            |
+----------------------------------------------------------------------------+


ETHlargement pills are currently being served. Please keep this window open, and we'll continue dosing your cards as needed.
Segmentation fault (core dumped)

Kernels in Fedora build with enabled option:

# cat /boot/config-4.12.8-200.fc25.x86_64 | grep CONFIG_IO_STRICT_DEVMEM
CONFIG_IO_STRICT_DEVMEM=y

I add boot-option  iomem=relaxed to kernel boot parameters and tool started succesfully.
$ cat /boot/grub2/grub.cfg | grep iomem
        linux16 /boot/vmlinuz-4.12.8-200.fc25.x86_64 root=UUID=65f7735b-cfb8-41cc-b29a-ecff9de5951d ro nomodeset rdblacklist=nouveau quiet LANG=en_US.UTF-8 iomem=relaxed
