### ISSUE TITLE
Question over mixed AMD - NVIDIA mining rig

### ISSUE THREAD

**Issue by dallapozzagiorgio** [OhGodACompany/OhGodAnETHlargementPill#81]
Good afternoon,

I would like to know how the pill works on a mixed mining rig (AMD - NVIDIA). Is there a way not to feed the pill to my AMD cards?

Best regards,
Giorgio

**Comment by OhGodABird** [comment]
The pill is supposed to be used without expert medical knowledge, and the only part that requires a bit of thinking is the need of --revA for some specific GPUs as prescribed, but other than that, it's just supposed to be run. It's limited to work only on the GPUs it's prescribed for, therefore it won't bother anything else.
