### ISSUE TITLE
Blank screen and  freeze on Desktop pc

### ISSUE THREAD

**Issue by i8088** [OhGodACompany/OhGodAnETHlargementPill#83]
Hello,  i got blank screen when i  start  pill    on my  desktop PC.  There is no running Claymore and  No OC .    
MSI  afterburner  4.5.0 with Default  GPU settings
GPU : EVGA 1080 Classified
Driver :   398.11
OS :   W10  x64

**Comment by OhGodABird** [comment]
Have you tried using --revA as prescribed?

**Comment by i8088** [comment]
@OhGodABird Yes I try as --revA . Nothing change

**Comment by OhGodABird** [comment]
Run your miner first, then run the pill with --revA after a few minutes. Although it really shouldn't be an issue, I've seen others reporting this method working for them on Windows. If that's working, then you can try skipping --revA to see if it's actually required.

If that doesn't help, then either:
1) You use --revA incorrectly
2) Your software environment is broken
3) Your GPU is one of the worst results of silicon lottery.

Point 1 is a matter of clarification, but the prescription has an obvious example, so I'm really not expecting this to be an issue.
Point 2 is something the pill can't control, it may be worthy to try something better for mining, which mostly means a Linux based OS.
Point 3 is absolutely not likely, but I'm interested in details if you get to this point. If that's the case, then it's likely hard to overclock without the pill to begin with.

**Comment by i8088** [comment]
Thank you.  Not its ok and work with 36mh/s without --revA  and   run sequence  : 1st miner , later  pill . 
Earlier  I was doing the reverse.
