### ISSUE TITLE
Commercial Version

### ISSUE THREAD

**Issue by mbhmirc** [OhGodACompany/OhGodAnETHlargementPill#9]
How do you buy it for other cards please?   What cards is it capable of doing and how much is it?

**Comment by mbhmirc** [comment]
ps with this being gddrx5 based i assume it can work for titanxp ?

**Comment by jimmykl** [comment]
It appears your wish was been answered a few minutes ago! https://bitcointalk.org/index.php?topic=3370685.msg35459802#msg35459802
