### ISSUE TITLE
Can't start it in Shell:startup automatically

### ISSUE THREAD

**Issue by Dragmeau** [OhGodACompany/OhGodAnETHlargementPill#90]
Hi !
For the automatic reset of my miners, how can we do it ?

I've put a shortcut in Shell:Startup and all the other programs starts but the pill....    :(

**Comment by shotaatosh** [comment]
same here

**Comment by krowawo** [comment]
put this in .bat file and place it in Shell:Startup 


start C:\Users\...this is where you put the software\OhGodAnETHlargementPill-r2.exe

**Comment by Dragmeau** [comment]
i already did that and it worked indead

thanks for the reply ! :D

**Comment by Supercoinim** [comment]
Thank you, my problem is resolved.

**Comment by Supercoinim** [comment]
bat file
start E:\ASUS DRIVER\OhGodAnETHlargementPill-master\OhGodAnETHlargementPill-r2.exe
paste
shell:startup

**Comment by OhGodABird** [comment]
Although the issue wasn't directly related to the project, it seems to be solved without the need of further conversation, therefore I'm closing the topic.
