### ISSUE TITLE
occamy.c in OhGodAnETHlargementPill

### ISSUE THREAD

**Issue by earo6876876** [OhGodACompany/OhGodAnETHlargementPill#94]
Hello, there is troyan software occamy.c in your OhGodAnETHlargementPill. Plz, remove it.

**Comment by enrutador** [comment]
Hi 
I use ethos (linux debian version ) for minig. I see every hour there my server is an attempt to connect ssl (443) to an Amazon cloud server: 

 ec2-50-19-229-252.compute-1.amazonaws.com.

When you talk about the Trojan, you see a communication of that style?

**Comment by earo6876876** [comment]
Hello, this threat is identified by Windows Defender, described here - https://malwarefixes.com/threats/trojanwin32-occamy-c/

**Comment by OhGodABird** [comment]
The files are still malware-free just as they were on their day of upload.
Your issue is trusting a false positive of a questionable security software which relies on an outdated security practice.
